### ISSUE TITLE
Putting the camera in a group works with the full source, does not with the minified one

### ISSUE THREAD

**Issue by bsotanyi** [xem/W#19]
As the title says.
When trying to put the camera in a group with the minified W code, the camera does not move anywhere.
Made a custom build from the full version, and it works, so probably some build step / option messed it up.

**Comment by xem** [comment]
Oh! Thanks for noticing, i'm gonna fix that.
If you make cool stuff with the lib we'd be happy to see it!

**Comment by bsotanyi** [comment]
Awesome, I'm trying out some libs for this year's js13 comp, and this is a very good contender.
I learned a lot from your works, thanks for providing so much for the community!

**Comment by xem** [comment]
The pleasure is for me, I love js13k and I'm happy if my tools can help anyone.
BTW, most of W.js 's magic come from my webgl mentors, stas and kchplr.
